[features]
seeds = false
skip-lint = false
[programs.localnet]
flipper = "HHbE9a2o19U1pTrRDwVp6ECh3WfZzCfGYb8BRf4zMT3B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/atreides/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
